name: Deploy to Netlify
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
concurrency:
  group: "netlify"
  cancel-in-progress: true
jobs:
  build-and-deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy to Netlify
        uses: zetaraku/netlify-actions/cli@master
        with:
          args: deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        id: netlify-deploy
    environment:
      name: production
      url: ${{ steps.netlify-deploy.outputs.NETLIFY_LIVE_URL }}
